// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCMnH3qBKUfg77u5VAeNmdWF-JJsnA78',
    appId: '1:34954487470:web:8f966bbd67b457568bef3f',
    messagingSenderId: '34954487470',
    projectId: 'flutter-app-8c92c',
    authDomain: 'flutter-app-8c92c.firebaseapp.com',
    databaseURL: 'https://flutter-app-8c92c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-8c92c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTVCO5o8XqLaoilyLC8cfGGpVNHU-7q0',
    appId: '1:34954487470:android:e8f401c72a3e5e268bef3f',
    messagingSenderId: '34954487470',
    projectId: 'flutter-app-8c92c',
    databaseURL: 'https://flutter-app-8c92c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-8c92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMeetvFKLyHk3Pi5cw_VuAWGj953kUfcg',
    appId: '1:34954487470:ios:8a2e58ad1e0ac7a08bef3f',
    messagingSenderId: '34954487470',
    projectId: 'flutter-app-8c92c',
    databaseURL: 'https://flutter-app-8c92c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-8c92c.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMeetvFKLyHk3Pi5cw_VuAWGj953kUfcg',
    appId: '1:34954487470:ios:8a2e58ad1e0ac7a08bef3f',
    messagingSenderId: '34954487470',
    projectId: 'flutter-app-8c92c',
    databaseURL: 'https://flutter-app-8c92c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-8c92c.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnCMnH3qBKUfg77u5VAeNmdWF-JJsnA78',
    appId: '1:34954487470:web:ec970c1983bb4fe88bef3f',
    messagingSenderId: '34954487470',
    projectId: 'flutter-app-8c92c',
    authDomain: 'flutter-app-8c92c.firebaseapp.com',
    databaseURL: 'https://flutter-app-8c92c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-8c92c.appspot.com',
  );
}
