// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCay8FRHVXN2aWA1p6Le815UFRmJL_xSQ4',
    appId: '1:210640355720:web:23df42ea013ae954a37a3d',
    messagingSenderId: '210640355720',
    projectId: 'employee-80f5d',
    authDomain: 'employee-80f5d.firebaseapp.com',
    databaseURL: 'https://employee-80f5d-default-rtdb.firebaseio.com',
    storageBucket: 'employee-80f5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOw3nuPXClttSOY9Kn808DMfBy5I-3Cs',
    appId: '1:210640355720:android:5bfbc3a805cdf164a37a3d',
    messagingSenderId: '210640355720',
    projectId: 'employee-80f5d',
    databaseURL: 'https://employee-80f5d-default-rtdb.firebaseio.com',
    storageBucket: 'employee-80f5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg6T2o9j6b2Wn6QR4-_r5bnrsFW4NoaWM',
    appId: '1:210640355720:ios:8ba6c68867edf61fa37a3d',
    messagingSenderId: '210640355720',
    projectId: 'employee-80f5d',
    databaseURL: 'https://employee-80f5d-default-rtdb.firebaseio.com',
    storageBucket: 'employee-80f5d.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg6T2o9j6b2Wn6QR4-_r5bnrsFW4NoaWM',
    appId: '1:210640355720:ios:8ba6c68867edf61fa37a3d',
    messagingSenderId: '210640355720',
    projectId: 'employee-80f5d',
    databaseURL: 'https://employee-80f5d-default-rtdb.firebaseio.com',
    storageBucket: 'employee-80f5d.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCay8FRHVXN2aWA1p6Le815UFRmJL_xSQ4',
    appId: '1:210640355720:web:23df42ea013ae954a37a3d',
    messagingSenderId: '210640355720',
    projectId: 'employee-80f5d',
    authDomain: 'employee-80f5d.firebaseapp.com',
    databaseURL: 'https://employee-80f5d-default-rtdb.firebaseio.com',
    storageBucket: 'employee-80f5d.appspot.com',
  );

}